all:
  vars:
    ansible_connection: ssh
    ansible_user: ansible
    ansible_port: 2222
    ansible_become: true
    ansible_ssh_private_key_file: /Users/dimi/.ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3
    jmxexporter_enabled: true
    kafka_controller_custom_properties:
      log.dirs: /home/ansible/logs
      log.dir: /home/ansible/logs/kafka/logs

kafka_controller:
  hosts:
    localhost:

# kafka_broker:
#   hosts:
#     ip-172-31-34-246.us-east-2.compute.internal:
#     ip-172-31-34-247.us-east-2.compute.internal:
#     ip-172-31-34-248.us-east-2.compute.internal:

# schema_registry:
#   hosts:
#     ip-172-31-34-246.us-east-2.compute.internal:

# kafka_rest:
#   hosts:
#     ip-172-31-34-246.us-east-2.compute.internal:

# ksql:
#   hosts:
#     ip-172-31-37-15.us-east-2.compute.internal:
#     ip-172-31-37-16.us-east-2.compute.internal:

# kafka_connect:
#   hosts:
#     ip-172-31-34-246.us-east-2.compute.internal:

# control_center:
#   hosts:
#     ip-172-31-37-15.us-east-2.compute.internal: