version: "3"
services:
  controller:
    image: confluentinc/cp-server:7.6.1
    hostname: controller
    container_name: controller-ldap
    volumes:
      - ./jaas:/etc/kafka/jaas/
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@controller:29092"
      KAFKA_LISTENERS: "INTERNAL://controller:29092,TEST://:9094"
      KAFKA_CONTROLLER_LISTENER_NAMES: "INTERNAL,TEST"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:SASL_PLAINTEXT,TEST:PLAINTEXT"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      CONFLUENT_TIER_METADATA_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CONFLUENT_TOPIC_REPLICATION_FACTOR: 1

      CONFLUENT_TELEMETRY_ENABLE: false
      CONFLUENT_REPORTERS_TELEMETRY_AUTO_ENABLE: "false"

      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN

      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/jaas/controller_jaas.conf

  broker:
    image: confluentinc/cp-server:7.6.1
    hostname: broker
    container_name: broker-ldap
    depends_on:
      - controller
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9101:9101"
    volumes:
      - ./jaas:/etc/kafka/jaas/
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_PROCESS_ROLES: "broker"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "INTERNAL"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@controller:29092"

      KAFKA_LISTENERS: "EXTERNAL://:9092,PLAINTEXT://broker:9093"
      KAFKA_ADVERTISED_LISTENERS: "EXTERNAL://broker:9092,PLAINTEXT://broker:9093"
      KAFKA_INTER_BROKER_LISTENER_NAME: "EXTERNAL"


      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost

      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      # KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      # KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-256

      # # KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      KAFKA_AUTHORIZER_CLASS_NAME: io.confluent.kafka.security.authorizer.ConfluentServerAuthorizer
      KAFKA_SUPER_USERS: User:kafka
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: true
      KAFKA_LDAP_JAVA_NAMING_PROVIDER_URL: ldap://openldap:389
      KAFKA_LDAP_JAVA_NAMING_SECURITY_AUTHENTICATION: SIMPLE
      KAFKA_LDAP_JAVA_NAMING_SECURITY_PRINCIPAL: cn=admin,dc=example,dc=com
      KAFKA_LDAP_JAVA_NAMING_SECURITY_CREDENTIALS: password
      KAFKA_LDAP_SEARCH_MODE: USERS
      KAFKA_LDAP_USER_SEARCH_BASE: DC=EXAMPLE,DC=COM
      KAFKA_LDAP_USER_OBJECT_CLASS: USER
      KAFKA_LDAP_USER_NAME_ATTRIBUTE: sAMAccountName
      KAFKA_LDAP_USER_MEMBEROF_ATTRIBUTE: memberOf
      KAFKA_LDAP_USER_MEMBEROF_ATTRIBUTE_PATTERN: CN=(.*),CN=USERS,.*

      KAFKA_OPTS: 
        -Djava.security.auth.login.config=/etc/kafka/jaas/broker_jaas.conf

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.5.0
    hostname: control-center
    container_name: control-center-ldap
    depends_on:
      - broker
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: "broker:29092"
      # CONTROL_CENTER_CONNECT_CONNECT-DEFAULT_CLUSTER: 'connect:8083'
      # CONTROL_CENTER_KSQL_KSQLDB1_URL: "http://ksqldb-server:8088"
      # CONTROL_CENTER_KSQL_KSQLDB1_ADVERTISED_URL: "http://localhost:8088"
      # CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021

  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    hostname: openldap
    ports:
      - "389:389"
      - "636:636"
    environment:
      LDAP_ORGANISATION: "Example"
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "password"
      LDAP_BASE_DN: "dc=example,dc=com"
    volumes:
      - ./ldap-records:/home/dimi
