version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper-sasl
    ports:
      - "2181:2181"
    volumes:
      - ./jaas:/etc/kafka/jaas/
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_AUTH_PROVIDER_SASL: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
      KAFKA_OPTS:
        -Djava.security.auth.login.config=/etc/kafka/jaas/zookeeper_jaas.conf

  broker:
    image: confluentinc/cp-server:7.5.0
    hostname: broker
    container_name: broker-sasl-zk
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    volumes:
      - ./jaas:/etc/kafka/secrets/
    environment:
      KAFKA_NODE_ID: 4
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT"
      KAFKA_LISTENERS: "EXTERNAL://:9092,INTERNAL://:9094"
      KAFKA_ADVERTISED_LISTENERS: "EXTERNAL://broker:9092,INTERNAL://broker:9094"
      KAFKA_INTER_BROKER_LISTENER_NAME: "EXTERNAL"

      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      # KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN

      # Replication factors
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      CONFLUENT_TIER_METADATA_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_TIER_METADATA_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CONFLUENT_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_CLUSTER_LINK_METADATA_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_CLUSTER_LINK_METADATA_TOPIC_REPLICATION_FACTOR: 1

      # # ACLS
      # KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      # KAFKA_SUPER_USERS: User:broker

      KAFKA_OPTS:
        -Djava.security.auth.login.config=/etc/kafka/secrets/broker_jaas.conf

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.6.0
    hostname: control-center
    container_name: control-center-sasl-zk
    depends_on:
      - broker
    ports:
      - "9021:9021"
    volumes:
      - ./jaas:/etc/kafka/secrets/
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:9092'

      CONFLUENT_TELEMETRY_ENABLE: false

      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021

      CONTROL_CENTER_STREAMS_SASL_MECHANISM: PLAIN
      CONTROL_CENTER_STREAMS_SECURITY_PROTOCOL: SASL_PLAINTEXT

      CONTROL_CENTER_STREAMS_SASL_JAAS_CONFIG:
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="admin"
        password="admin-secret";

#      CONTROL_CENTER_OPTS:
#        -Djava.security.auth.login.config=/etc/kafka/secrets/ccc_jaas.conf




