version: "3"
services:
  controller-1:
    image: confluentinc/cp-server:7.6.0
    hostname: controller-1
    container_name: controller-1-sasl
    volumes:
      - ./jaas:/etc/kafka/secrets/
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@controller-1:29092"
      KAFKA_LISTENERS: "INTERNAL://controller-1:29092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "INTERNAL"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:SASL_PLAINTEXT"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      CONFLUENT_TIER_METADATA_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CONFLUENT_TOPIC_REPLICATION_FACTOR: 1

      #      CONFLUENT_METRICS_REPORTER_SASL_MECHANISM: PLAIN
      #      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: localhost:19092

      CONFLUENT_TELEMETRY_ENABLE: false


      CONFLUENT_REPORTERS_TELEMETRY_AUTO_ENABLE: 'false'

      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN

      KAFKA_OPTS:
        -Djava.security.auth.login.config=/etc/kafka/secrets/controller_jaas.conf

  broker-1:
    image: confluentinc/cp-server:7.6.0
    hostname: broker-1
    container_name: broker-1-sasl
    depends_on:
      - controller-1
    ports:
      - "9092:9092"
      - "9101:9101"
    volumes:
      - ./jaas:/etc/kafka/secrets/
    environment:
      KAFKA_NODE_ID: 4
      KAFKA_PROCESS_ROLES: "broker"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@controller-1:29092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "INTERNAL"

      KAFKA_LISTENERS: "EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "EXTERNAL://broker-1:9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "EXTERNAL"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      CONFLUENT_TIER_METADATA_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CONFLUENT_TOPIC_REPLICATION_FACTOR: 1

      #      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      #      CONFLUENT_METRICS_REPORTER_SASL_MECHANISM: PLAIN
      #      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: localhost:29092

      CONFLUENT_TELEMETRY_ENABLE: false

      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN

      KAFKA_OPTS:
        -Djava.security.auth.login.config=/etc/kafka/secrets/broker_jaas.conf

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.6.0
    hostname: control-center
    container_name: control-center-sasl
    depends_on:
      - broker-1
    ports:
      - "9021:9021"
    volumes:
      - ./jaas:/etc/kafka/secrets/
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker-1:9092'
      #      CONTROL_CENTER_CONNECT_CONNECT-DEFAULT_CLUSTER: 'connect:8083'
      #      CONTROL_CENTER_CONNECT_HEALTHCHECK_ENDPOINT: '/connectors'
      #      CONTROL_CENTER_KSQL_KSQLDB1_URL: "http://ksqldb-server:8088"
      #      CONTROL_CENTER_KSQL_KSQLDB1_ADVERTISED_URL: "http://localhost:8088"
      #      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"

      CONFLUENT_TELEMETRY_ENABLE: false

      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021

      CONTROL_CENTER_STREAMS_SASL_MECHANISM: PLAIN
      CONTROL_CENTER_STREAMS_SECURITY_PROTOCOL: SASL_PLAINTEXT

      CONTROL_CENTER_STREAMS_SASL_JAAS_CONFIG:
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="admin"
        password="admin-secret";

#      CONTROL_CENTER_OPTS:
#        -Djava.security.auth.login.config=/etc/kafka/secrets/ccc_jaas.conf
