
@host = http://localhost:8081

# @name registerKey
POST {{host}}/subjects/key/versions HTTP/1.1
Accept: application/vnd.schemaregistry.v1+json, application/vnd.schemaregistry+json, application/json
Content-Type: application/vnd.schemaregistry.v1+json
Authorization: Basic fred:letmein

< ./schemas/key.json

###

# @name registerValue
POST {{host}}/subjects/value/versions HTTP/1.1
Accept: application/vnd.schemaregistry.v1+json, application/vnd.schemaregistry+json, application/json
Content-Type: application/vnd.schemaregistry.v1+json

< ./schemas/value.json

###
GET {{host}}/subjects
Authorization: Basic fred:letmein
###
GET {{host}}/schemas
###
GET {{host}}/schemas/ids/1/versions
###
GET {{host}}/subjects/value/versions/1
###
GET {{host}}/subjects/key/versions/1
###
GET {{host}}/subjects/value/versions/
###
GET {{host}}/subjects/key/versions/
