services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    restart: always
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker-1:
    image: confluentinc/cp-server:7.5.1
    restart: always
    hostname: broker-1
    container_name: broker-1
    depends_on:
      - zookeeper
    ports:
      - "8092:8092"
      - "9092:9092"
    volumes:
      - ./config:/etc/kafka/demo
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_BROKER_RACK: west
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,TOKEN:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-1:19092,TOKEN://broker-1:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_METRICS_REPORTER: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker-ccc:19098
      KAFKA_CONFLUENT_MONITORING_INTERCEPTER_BOOTSTRAP_SERVERS: broker-ccc:19098
      KAFKA_JMX_PORT: 8092
      
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  broker-2:
    image: confluentinc/cp-server:7.5.1
    restart: always
    hostname: broker-2
    container_name: broker-2
    depends_on:
      - zookeeper
    ports:
      - "8093:8093"
      - "9093:9093"
    volumes:
      - ./config:/etc/kafka/demo
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_BROKER_RACK: west
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,TOKEN:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-2:19093,TOKEN://broker-2:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_METRICS_REPORTER: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_ENABLE: "true"
      KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker-ccc:19098
      KAFKA_CONFLUENT_MONITORING_INTERCEPTER_BOOTSTRAP_SERVERS: broker-ccc:19098
      KAFKA_JMX_PORT: 8093

      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  broker-3:
    image: confluentinc/cp-server:7.5.1
    restart: always
    hostname: broker-3
    container_name: broker-3
    depends_on:
      - zookeeper
    ports:
      - "8094:8094"
      - "9094:9094"
    volumes:
      - ./config:/etc/kafka/demo
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_BROKER_RACK: west
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,TOKEN:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-3:19094,TOKEN://broker-3:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_METRICS_REPORTER: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_ENABLE: "true"
      KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker-ccc:19098
      KAFKA_CONFLUENT_MONITORING_INTERCEPTER_BOOTSTRAP_SERVERS: broker-ccc:19098
      KAFKA_JMX_PORT: 8094

      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  zookeeper-ccc:
    image: confluentinc/cp-zookeeper:7.5.1
    hostname: zookeeper-ccc
    container_name: zookeeper-ccc
    ports:
      - "2188:2188"
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2188
      ZOOKEEPER_SERVERS: zookeeper-ccc:2888:3888

  broker-ccc:
    image: confluentinc/cp-server:7.5.1
    restart: always
    hostname: broker-ccc
    container_name: broker-ccc
    depends_on:
      - zookeeper-ccc
    ports:
      - "9098:9098"
      - "8098:8098"
    volumes:
      - ./config:/etc/kafka/demo
    environment:
      KAFKA_BROKER_ID: 8
      KAFKA_BROKER_RACK: metrics

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,TOKEN:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-ccc:19098,TOKEN://broker-ccc:9098
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-ccc:2188'
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker-ccc:19098
      KAFKA_JMX_PORT: 8098
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.5.1
    hostname: control-center
    container_name: control-center
    restart: always
    depends_on:
      - broker-ccc
      - zookeeper-ccc
    ports:
      - "9021:9021"
    environment:

      CONTROL_CENTER_BOOTSTRAP_SERVERS: broker-ccc:19098
      CONTROL_CENTER_KAFKA_MRC_BOOTSTRAP_SERVERS: broker-1:9092,broker-2:9092,broker-3:9092
      CONTROL_CENTER_KAFKA_METRICS_BOOTSTRAP_SERVERS: broker-ccc:19098
      
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONFLUENT_MONITORING_INTERCEPTOR_TOPIC_REPLICATION: 1
      CONFLUENT_CONTROLCENTER_INTERNAL_TOPICS_REPLICATION: 1
      CONFLUENT_CONTROLCENTER_COMMAND_TOPIC_REPLICATION: 1
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      CONFLUENT_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      PORT: 9021

volumes:
  mi3: {}
